### ISSUE TITLE
Invalid type specifier crash with GRC 3.11

### ISSUE THREAD

**Issue by DJRaov** [drmpeg/gr-dvbs2#11]
Hello,
Just decided to try DVB-S2 again, and was met with a nice `[*** LOG ERROR #0001 ***] [2022-05-31 13:32:19] [ldpc_bb] {invalid type specifier}` upon trying to launch the flowchart. GRC version is 3.11.0.0git-154-g9734aaee compiled from source just yesterday.
Any fixes I could attempt to make it work again?

**Comment by drmpeg** [comment]
Are you sure you're actually running GNU Radio Companion v3.11.0.0git-154-g9734aaee? That bug was fixed with commit https://github.com/gnuradio/gnuradio/commit/ef3ea5cd0121e850d4f81e1b2d05e779928e5eb7

**Comment by DJRaov** [comment]
Possibly not entirely. Forgot to uninstall 3.10.4 I installed from AUR, uninstalling and reinstalling the github version worked. Thanks for pointing this out!
