### ISSUE TITLE
Does it support Gnuradio v3.9.0 and python3?

### ISSUE THREAD

**Issue by guokr321** [drmpeg/gr-dvbs2#7]
Hello,
Using Gnuradio v3.9.0 and python 3.6.9, cmake will have error:
-- 
-- Checking for module SWIG
-- Found SWIG version 3.0.12.
-- User set python executable /usr/bin/python2.7
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found suitable exact version "2.7.17") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found suitable version "2.7.17", minimum required is "2") 
CMake Error at /usr/local/lib/cmake/gnuradio/GrSwig.cmake:227 (GR_LIBTOOL):
  Unknown CMake command "GR_LIBTOOL".
Call Stack (most recent call first):
  swig/CMakeLists.txt:55 (GR_SWIG_INSTALL)

**Comment by drmpeg** [comment]
Are you intending to use the vcm branch? If not, then gr-dvbs2 is already built-in to GNU Radio 3.9.

**Comment by guokr321** [comment]
> Are you intending to use the vcm branch? If not, then gr-dvbs2 is already built-in to GNU Radio 3.9.

I use master branch, cmake will be error.

**Comment by drmpeg** [comment]
All the functionality of gr-dvbs2 has been ported into GNU Radio itself long ago. See the Digital Television category in gnuradio-companion.

![image](https://user-images.githubusercontent.com/5397196/86554240-e40ab180-bf01-11ea-9d4a-b765800369ac.png)

Example flow graph is in:

gnuradio/gr-dtv/examples/dvbs2_tx.grc

or

<install_dir>/share/gnuradio/examples/dtv/dvbs2_tx.grc

**Comment by guokr321** [comment]
Yes, I know it. my question is cmake error under gunuradio v3.9.0
