### ISSUE TITLE
VCM/ACM mode validation

### ISSUE THREAD

**Issue by staresatscreen** [drmpeg/gr-dvbs2#9]
Hello there, 
Can I ask how did you validate the ACM behaviour? 
I've generated the test stream with the provided flowgraph (dvbs2_tx.grc). I've managed to detect physical frames and descramble them, but pilots are still spread across all quadrants; while they're expected in first quadrant only.
Thank you!

**Comment by drmpeg** [comment]
It's been validated with hardware receivers. Specifically the Novra S300V and Digital Devices Max SX8 (and the Ayecka SR-1 for the DVB-GSE flow graph).

As for the pilots, they're scrambled too. Perhaps you're not accounting for that. Also, the PL header is PI/4 BPSK modulated, so you'll see those symbols in all four quadrants.

**Comment by staresatscreen** [comment]
OK, thank you for the information!
